# Global settings for the Helm chart
replicaCount: 2

image:
  repository: tdksoft341/api-gateway
  tag: "latest"
  pullPolicy: IfNotPresent

spring:
  profile: default  # A neutral profile for base configuration
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    memory: 256Mi
    cpu: 200m

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  hosts:
    - host: "tdk.domain.com"
      paths:
        - path: /
          pathType: Prefix
        - path: /api
          pathType: Prefix

postgresql:
  enabled: false

serviceAccount:
  create: true
  automount: true