apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kehe0014/springboot-microservices-helm.git'
    targetRevision: main
    path: helm-charts/charts/api-gateway
    helm:
      valueFiles:
        - ../../environments/staging/api-gateway-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
