apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kehe0014/springboot-microservices-helm.git
    targetRevision: HEAD
    path: helm-charts/charts/api-gateway
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: api-gateway
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  
  info:
    - name: Description
      value: API Gateway Microservice for Staging Environment