apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kehe0014/springboot-microservices-helm.git
    targetRevision: HEAD
    path: helm-charts/charts/product-service
    helm:
      valueFiles:
        - values.yaml
      # Optional: If you need to override values for staging
      # values: |
      #   replicaCount: 2
      #   image:
      #     tag: staging-latest
  
  destination:
    server: https://kubernetes.default.svc
    namespace: product-service
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  
  info:
    - name: Description
      value: Product Service Microservice for Staging Environment