name: Reusable Build and Deploy

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: tdksoft341

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        working-directory: ./services/${{ inputs.service_name }}
        run: mvn -B clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ inputs.service_name }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ inputs.service_name }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ inputs.service_name }}:latest

  update-gitops-manifest:
    name: Update GitOps Manifest
    needs: build-and-push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Update manifest for ${{ inputs.service_name }}
        run: |
          # Mise à jour du tag d'image dans le manifeste ArgoCD
          yq eval -i ".spec.source.helm.parameters |= map(select(.name == \"image.tag\").value = \"${{ github.sha }}\" | .)" "infra/gitops/applications/staging/${{ inputs.service_name }}.yaml"

      - name: Create Pull Request for GitOps update
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "ci: deploy ${{ inputs.service_name }} image ${{ github.sha }}"
          title: "Deploy new ${{ inputs.service_name }} image"
          body: "This PR updates the GitOps manifest to deploy version `${{ github.sha }}` of the ${{ inputs.service_name }}."
          branch: "deploy/${{ inputs.service_name }}-${{ github.sha }}"
          base: "main"