name: Lint and Test

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev

jobs:
  lint-helm:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Lint all Helm charts
        run: |
          for chart in helm-charts/charts/*; do
            echo "Linting $chart"
            helm lint "$chart"
          done

  test-services:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, user-service, product-service]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Navigate to service
        run: cd services/${{ matrix.service }}

      - name: Run Tests
        run: ./gradlew test
        working-directory: services/${{ matrix.service }}
